"""Tests for the taskforce init wizard command."""

import os
from pathlib import Path
from unittest.mock import AsyncMock, patch

import pytest
import yaml

from taskforce.api.cli.commands.init import (
    EXTRAS,
    PROFILES,
    PROVIDERS,
    InitConfig,
    _generate_env_file,
    _generate_llm_config,
    _generate_profile_override,
    _setup_workspace,
)


class TestInitConfig:
    """Tests for InitConfig dataclass."""

    def test_defaults(self) -> None:
        config = InitConfig()
        assert config.provider == "openai"
        assert config.api_keys == {}
        assert config.model_aliases == {}
        assert config.profile == "dev"
        assert config.extras == []
        assert config.work_dir == Path(".taskforce")

    def test_custom_values(self) -> None:
        config = InitConfig(
            provider="anthropic",
            api_keys={"ANTHROPIC_API_KEY": "test-key"},
            profile="butler",
        )
        assert config.provider == "anthropic"
        assert config.api_keys["ANTHROPIC_API_KEY"] == "test-key"
        assert config.profile == "butler"


class TestProviderDefinitions:
    """Tests for provider configuration constants."""

    def test_all_providers_have_required_fields(self) -> None:
        required_fields = {"name", "env_keys", "default_models", "prefix"}
        for provider_id, provider in PROVIDERS.items():
            assert required_fields <= set(provider.keys()), (
                f"Provider '{provider_id}' missing fields"
            )

    def test_all_providers_have_model_aliases(self) -> None:
        required_aliases = {"main", "powerful", "fast"}
        for provider_id, provider in PROVIDERS.items():
            assert required_aliases <= set(provider["default_models"].keys()), (
                f"Provider '{provider_id}' missing model aliases"
            )

    def test_ollama_has_no_env_keys(self) -> None:
        assert PROVIDERS["ollama"]["env_keys"] == {}


class TestGenerateEnvFile:
    """Tests for .env file generation."""

    def test_generates_env_with_keys(self, tmp_path: Path) -> None:
        config = InitConfig(
            api_keys={"OPENAI_API_KEY": "sk-test123", "GITHUB_TOKEN": "ghp_test"},
        )
        target = tmp_path / ".env"
        _generate_env_file(config, target)

        content = target.read_text()
        assert "OPENAI_API_KEY=sk-test123" in content
        assert "GITHUB_TOKEN=ghp_test" in content

    def test_generates_env_without_keys(self, tmp_path: Path) -> None:
        config = InitConfig(api_keys={})
        target = tmp_path / ".env"
        _generate_env_file(config, target)

        content = target.read_text()
        assert "Generated by 'taskforce init'" in content

    def test_adds_optional_placeholders(self, tmp_path: Path) -> None:
        config = InitConfig(api_keys={"OPENAI_API_KEY": "sk-test"})
        target = tmp_path / ".env"
        _generate_env_file(config, target)

        content = target.read_text()
        assert "# GITHUB_TOKEN=" in content


class TestGenerateLlmConfig:
    """Tests for llm_config.yaml generation."""

    def test_generates_valid_yaml(self, tmp_path: Path) -> None:
        config = InitConfig(
            provider="openai",
            model_aliases={"main": "gpt-4.1-mini", "powerful": "gpt-4.1", "fast": "gpt-4.1-nano"},
        )
        target = tmp_path / "llm_config.yaml"
        _generate_llm_config(config, target)

        data = yaml.safe_load(target.read_text())
        assert data["default_model"] == "main"
        assert data["models"]["main"] == "gpt-4.1-mini"
        assert data["models"]["powerful"] == "gpt-4.1"
        assert data["routing"]["enabled"] is True

    def test_anthropic_includes_model_params(self, tmp_path: Path) -> None:
        config = InitConfig(
            provider="anthropic",
            model_aliases={
                "main": "anthropic/claude-sonnet-4-6",
                "powerful": "anthropic/claude-opus-4-6",
                "fast": "anthropic/claude-haiku-4-5-20251001",
            },
        )
        target = tmp_path / "llm_config.yaml"
        _generate_llm_config(config, target)

        data = yaml.safe_load(target.read_text())
        assert "model_params" in data


class TestGenerateProfileOverride:
    """Tests for profile override generation."""

    def test_generates_valid_profile(self, tmp_path: Path) -> None:
        config = InitConfig(
            profile="coding_agent",
            work_dir=Path(".taskforce"),
        )
        target = tmp_path / "profile.yaml"
        _generate_profile_override(config, target)

        data = yaml.safe_load(target.read_text())
        assert data["profile"] == "coding_agent"
        assert "llm" in data
        assert "persistence" in data


class TestSetupWorkspace:
    """Tests for workspace directory setup."""

    def test_creates_workspace_directory(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.chdir(tmp_path)
        config = InitConfig(
            provider="openai",
            api_keys={"OPENAI_API_KEY": "sk-test"},
            model_aliases={"main": "gpt-4.1-mini", "powerful": "gpt-4.1", "fast": "gpt-4.1-nano"},
            profile="dev",
            work_dir=Path(".taskforce"),
        )

        _setup_workspace(config)

        assert (tmp_path / ".taskforce" / "config").is_dir()
        assert (tmp_path / ".env").is_file()
        assert (tmp_path / ".taskforce" / "config" / "llm_config.yaml").is_file()
        assert (tmp_path / ".taskforce" / "config" / "profile.yaml").is_file()

    def test_preserves_existing_env(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.chdir(tmp_path)
        env_file = tmp_path / ".env"
        env_file.write_text("EXISTING=value\n")

        config = InitConfig(
            provider="openai",
            api_keys={"OPENAI_API_KEY": "sk-new"},
            model_aliases={"main": "gpt-4.1-mini"},
            work_dir=Path(".taskforce"),
        )

        # Mock typer.confirm to return False (don't overwrite)
        with patch("taskforce.api.cli.commands.init.typer.confirm", return_value=False):
            _setup_workspace(config)

        # Original content preserved
        assert env_file.read_text() == "EXISTING=value\n"

    def test_adds_env_to_gitignore(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.chdir(tmp_path)
        gitignore = tmp_path / ".gitignore"
        gitignore.write_text("*.pyc\n")

        config = InitConfig(
            provider="openai",
            api_keys={},
            model_aliases={"main": "gpt-4.1-mini"},
            work_dir=Path(".taskforce"),
        )

        _setup_workspace(config)

        content = gitignore.read_text()
        assert ".env" in content
